In [3]:
import numpy as np
import pandas as pd
from IPython.display import display

pd.set_option("display.precision", 2)
from matplotlib import pyplot as plt

# Graphics in SVG format are more sharp and legible
%config InlineBackend.figure_format = 'svg'

In [10]:
m_plus = pd.read_json("./master_plus.json").T
d_plus = pd.read_json("./diamond_plus.json").T

In [11]:
m_plus = m_plus.sort_values(by=6, ascending=False)
display(m_plus.head(25))

              0     1     2     3     4     5     6
Dr. Mundo  0.55  0.48  0.50  0.54  0.58  0.62  0.70
Naafiri    0.33  0.51  0.49  0.50  0.59  0.63  0.69
Sona       0.50  0.51  0.56  0.57  0.55  0.55  0.64
Gwen       0.57  0.51  0.54  0.56  0.55  0.57  0.64
Kayle      0.47  0.52  0.49  0.54  0.60  0.59  0.64
Fizz       0.67  0.59  0.54  0.55  0.56  0.58  0.63
Rengar     0.58  0.55  0.53  0.56  0.58  0.60  0.62
Yuumi      0.45  0.49  0.46  0.52  0.55  0.56  0.62
Shaco      0.68  0.59  0.54  0.54  0.57  0.59  0.61
Skarner    0.37  0.50  0.51  0.54  0.61  0.67  0.61
Pantheon   0.61  0.54  0.52  0.54  0.55  0.55  0.61
Fiora      0.58  0.54  0.54  0.55  0.57  0.58  0.61
Kassadin   0.45  0.52  0.50  0.57  0.61  0.60  0.61
Volibear   0.58  0.51  0.55  0.54  0.53  0.56  0.61
Maokai     0.38  0.44  0.51  0.55  0.59  0.59  0.61
Zilean     0.54  0.54  0.54  0.55  0.57  0.57  0.60
Samira     0.55  0.55  0.50  0.55  0.57  0.56  0.60
Nilah      0.55  0.55  0.54  0.56  0.57  0.60  0.60
Zed        0.47  0.52  0.51  0.54  0.55  0.56  0.60
Evelynn    0.62  0.63  0.54  0.55  0.56  0.58  0.60
Vladimir   0.49  0.56  0.55  0.55  0.56  0.59  0.60
Senna      0.54  0.53  0.57  0.55  0.55  0.57  0.60
Annie      0.45  0.50  0.53  0.57  0.58  0.58  0.60
Quinn      0.49  0.58  0.58  0.56  0.58  0.53  0.59
Veigar     0.51  0.51  0.52  0.54  0.55  0.58  0.59

In [12]:
d_plus = d_plus.sort_values(by=6, ascending=False)
display(m_plus.head(35))

                 0     1     2     3     4     5     6
Dr. Mundo     0.55  0.48  0.50  0.54  0.58  0.62  0.70
Naafiri       0.33  0.51  0.49  0.50  0.59  0.63  0.69
Sona          0.50  0.51  0.56  0.57  0.55  0.55  0.64
Gwen          0.57  0.51  0.54  0.56  0.55  0.57  0.64
Kayle         0.47  0.52  0.49  0.54  0.60  0.59  0.64
Fizz          0.67  0.59  0.54  0.55  0.56  0.58  0.63
Rengar        0.58  0.55  0.53  0.56  0.58  0.60  0.62
Yuumi         0.45  0.49  0.46  0.52  0.55  0.56  0.62
Shaco         0.68  0.59  0.54  0.54  0.57  0.59  0.61
Skarner       0.37  0.50  0.51  0.54  0.61  0.67  0.61
Pantheon      0.61  0.54  0.52  0.54  0.55  0.55  0.61
Fiora         0.58  0.54  0.54  0.55  0.57  0.58  0.61
Kassadin      0.45  0.52  0.50  0.57  0.61  0.60  0.61
Volibear      0.58  0.51  0.55  0.54  0.53  0.56  0.61
Maokai        0.38  0.44  0.51  0.55  0.59  0.59  0.61
Zilean        0.54  0.54  0.54  0.55  0.57  0.57  0.60
Samira        0.55  0.55  0.50  0.55  0.57  0.56  0.60
Nilah         0.55  0.55  0.54  0.56  0.57  0.60  0.60
Zed           0.47  0.52  0.51  0.54  0.55  0.56  0.60
Evelynn       0.62  0.63  0.54  0.55  0.56  0.58  0.60
Vladimir      0.49  0.56  0.55  0.55  0.56  0.59  0.60
Senna         0.54  0.53  0.57  0.55  0.55  0.57  0.60
Annie         0.45  0.50  0.53  0.57  0.58  0.58  0.60
Quinn         0.49  0.58  0.58  0.56  0.58  0.53  0.59
Veigar        0.51  0.51  0.52  0.54  0.55  0.58  0.59
Milio         0.54  0.51  0.54  0.55  0.56  0.58  0.59
Swain         0.56  0.52  0.54  0.53  0.53  0.53  0.59
Akshan        0.65  0.61  0.59  0.56  0.56  0.55  0.59
Lillia        0.55  0.48  0.52  0.54  0.55  0.56  0.59
Kha'Zix       0.53  0.52  0.52  0.55  0.58  0.58  0.59
Twisted Fate  0.52  0.53  0.57  0.57  0.56  0.57  0.59
Taric         0.54  0.56  0.58  0.57  0.54  0.55  0.59
Tahm Kench    0.51  0.56  0.51  0.57  0.55  0.53  0.59
Aurelion Sol  0.44  0.48  0.51  0.56  0.60  0.60  0.58
Teemo         0.49  0.50  0.53  0.53  0.58  0.59  0.58