In [27]:
import numpy as np
import pandas as pd
from IPython.display import display

pd.set_option("display.precision", 2)
from matplotlib import pyplot as plt

# Graphics in SVG format are more sharp and legible
%config InlineBackend.figure_format = 'svg'

In [28]:
m_plus = pd.read_json("./master_plus.json").T
d_plus = pd.read_json("./diamond_plus.json").T
top_m_plus = pd.read_json("./top_master_plus.json").T
bot_d_plus = pd.read_json("./bot_d_plus.json").T

In [29]:
m_plus = m_plus.sort_values(by=6, ascending=False)
display(m_plus.head(25))

                 0     1     2     3     4     5     6
Dr. Mundo     0.67  0.46  0.51  0.55  0.57  0.60  0.70
Naafiri       0.44  0.48  0.49  0.51  0.60  0.62  0.66
Kayle         0.47  0.53  0.49  0.54  0.60  0.60  0.66
Skarner       0.39  0.47  0.51  0.53  0.59  0.65  0.65
Gwen          0.60  0.51  0.54  0.57  0.55  0.58  0.65
Rengar        0.61  0.56  0.53  0.57  0.59  0.60  0.64
Volibear      0.52  0.51  0.54  0.53  0.52  0.56  0.64
Sona          0.47  0.52  0.56  0.57  0.55  0.56  0.64
Maokai        0.39  0.45  0.50  0.55  0.59  0.60  0.62
Fiora         0.57  0.53  0.54  0.56  0.56  0.58  0.62
Aurelion Sol  0.45  0.48  0.52  0.55  0.60  0.60  0.62
Teemo         0.43  0.50  0.53  0.54  0.59  0.59  0.62
Kassadin      0.43  0.51  0.50  0.57  0.61  0.60  0.62
Yuumi         0.44  0.49  0.45  0.52  0.54  0.55  0.62
Taric         0.56  0.54  0.57  0.58  0.54  0.55  0.61
Fizz          0.64  0.58  0.55  0.55  0.55  0.58  0.61
Amumu         0.42  0.46  0.48  0.51  0.56  0.54  0.61
Zed           0.47  0.51  0.51  0.54  0.55  0.56  0.61
Vladimir      0.49  0.56  0.55  0.55  0.56  0.59  0.60
Annie         0.42  0.50  0.53  0.57  0.58  0.59  0.60
Akshan        0.65  0.61  0.58  0.55  0.57  0.54  0.60
Senna         0.54  0.54  0.57  0.55  0.55  0.56  0.60
Pantheon      0.57  0.54  0.52  0.54  0.56  0.54  0.59
Twisted Fate  0.55  0.52  0.58  0.57  0.56  0.56  0.59
Swain         0.54  0.53  0.54  0.52  0.53  0.52  0.59

In [22]:
d_plus = d_plus.sort_values(by=5, ascending=False)
display(m_plus.head(35))

                 0     1     2     3     4     5     6
Kayle         0.49  0.50  0.47  0.51  0.58  0.59  0.60
Aurelion Sol  0.41  0.42  0.46  0.52  0.57  0.59  0.60
Kassadin      0.46  0.48  0.45  0.54  0.58  0.58  0.58
Shaco         0.60  0.58  0.50  0.50  0.53  0.55  0.57
Teemo         0.50  0.47  0.50  0.50  0.53  0.56  0.57
Dr. Mundo     0.45  0.44  0.50  0.53  0.55  0.56  0.57
Ornn          0.51  0.48  0.48  0.53  0.57  0.58  0.57
Yuumi         0.48  0.50  0.45  0.48  0.52  0.55  0.56
Rengar        0.51  0.49  0.47  0.50  0.54  0.56  0.56
Sona          0.45  0.48  0.53  0.55  0.55  0.54  0.56
Rammus        0.53  0.51  0.51  0.54  0.56  0.57  0.56
Nasus         0.51  0.56  0.52  0.53  0.55  0.55  0.56
Vladimir      0.51  0.53  0.51  0.52  0.53  0.55  0.56
Naafiri       0.50  0.47  0.48  0.52  0.56  0.56  0.56
Evelynn       0.57  0.61  0.51  0.51  0.53  0.54  0.56
Skarner       0.43  0.45  0.48  0.51  0.55  0.56  0.56
Annie         0.43  0.45  0.51  0.54  0.57  0.58  0.56
Fiora         0.50  0.51  0.51  0.53  0.53  0.54  0.56
Senna         0.50  0.51  0.54  0.53  0.52  0.53  0.56
Gwen          0.50  0.46  0.50  0.52  0.53  0.54  0.56
Veigar        0.46  0.50  0.51  0.52  0.53  0.55  0.56
Maokai        0.45  0.42  0.48  0.52  0.56  0.56  0.56
Fizz          0.57  0.57  0.53  0.53  0.54  0.55  0.55
Milio         0.48  0.48  0.50  0.52  0.54  0.54  0.55
Cho'Gath      0.50  0.48  0.49  0.51  0.53  0.55  0.55
Nilah         0.53  0.52  0.50  0.52  0.55  0.56  0.55
Vayne         0.51  0.52  0.52  0.54  0.55  0.55  0.55
Twitch        0.52  0.57  0.52  0.53  0.54  0.54  0.55
Renata Glasc  0.48  0.47  0.50  0.53  0.55  0.55  0.55
Miss Fortune  0.51  0.50  0.51  0.53  0.54  0.56  0.55
Aphelios      0.48  0.43  0.46  0.48  0.51  0.52  0.55
Twisted Fate  0.50  0.50  0.54  0.54  0.53  0.54  0.54
Riven         0.51  0.49  0.51  0.53  0.54  0.54  0.54
Rakan         0.49  0.49  0.51  0.54  0.55  0.55  0.54
Taric         0.52  0.53  0.55  0.54  0.54  0.54  0.54

In [17]:
top_m_plus = top_m_plus.sort_values(by=6, ascending=False)
top_m_plus.head(15)

                 0     1     2     3     4     5     6
Ziggs         1.00  0.52  0.65  0.46  0.38  0.40  1.00
Aphelios      1.00  0.46  0.31  0.62  0.30  0.80  1.00
Janna         0.50  0.39  0.51  0.59  0.43  0.62  1.00
Nocturne      0.33  0.51  0.52  0.62  0.44  0.56  1.00
Fizz          1.00  0.38  0.53  0.45  0.48  0.64  1.00
Ezreal        0.50  0.38  0.47  0.49  0.30  0.83  1.00
Senna         0.40  0.45  0.61  0.50  0.48  0.47  1.00
Tristana      0.40  0.54  0.55  0.53  0.48  0.53  0.78
Sejuani       0.43  0.56  0.52  0.52  0.58  0.56  0.75
Bel'Veth      0.67  0.64  0.60  0.48  0.49  0.38  0.75
Twisted Fate  1.00  0.56  0.62  0.61  0.59  0.69  0.75
Aurelion Sol  0.50  0.45  0.49  0.51  0.55  0.57  0.75
Draven        0.17  0.45  0.56  0.54  0.49  0.59  0.71
Kai'Sa        0.50  0.41  0.54  0.58  0.50  0.63  0.71
Swain         0.75  0.57  0.57  0.57  0.54  0.57  0.69

In [26]:
bot_d_plus = bot_d_plus.sort_values(by=6, ascending=False)
display(bot_d_plus.head(25))

                0     1     2     3     4     5     6
Zac          0.17  0.53  0.51  0.56  0.60  0.50  1.00
Blitzcrank   0.14  0.03  0.16  0.28  0.46  0.52  0.86
Vi           0.50  0.18  0.21  0.55  0.48  0.50  0.75
Alistar      0.14  0.12  0.37  0.48  0.46  0.42  0.71
Bel'Veth     0.43  0.48  0.61  0.54  0.54  0.48  0.70
Rammus       0.25  0.56  0.49  0.53  0.55  0.57  0.69
Wukong       0.43  0.47  0.49  0.48  0.61  0.51  0.68
Nami         0.04  0.08  0.30  0.40  0.58  0.59  0.67
Xin Zhao     0.33  0.39  0.55  0.47  0.56  0.45  0.67
Darius       0.30  0.35  0.34  0.50  0.53  0.56  0.65
Galio        0.60  0.41  0.38  0.43  0.59  0.71  0.65
Ryze         0.40  0.38  0.41  0.51  0.56  0.53  0.63
Mordekaiser  0.29  0.49  0.45  0.50  0.56  0.55  0.63
Aatrox       0.50  0.33  0.38  0.43  0.52  0.56  0.62
Nasus        0.29  0.48  0.49  0.48  0.49  0.47  0.62
Rengar       0.64  0.60  0.56  0.54  0.55  0.54  0.62
Teemo        0.29  0.32  0.40  0.47  0.47  0.54  0.61
Riven        0.29  0.37  0.41  0.50  0.55  0.56  0.61
Vladimir     0.60  0.47  0.46  0.49  0.52  0.53  0.61
Sett         0.50  0.51  0.57  0.55  0.55  0.56  0.60
LeBlanc      0.50  0.26  0.39  0.48  0.47  0.49  0.60
Sejuani      0.38  0.42  0.50  0.60  0.38  0.57  0.60
Kindred      0.42  0.50  0.46  0.51  0.51  0.54  0.60
Annie        0.29  0.43  0.44  0.51  0.53  0.58  0.58
Yone         0.54  0.50  0.46  0.47  0.50  0.51  0.58